// Shared Arabic translation of answer options for the seeded question banks.
// Keyed by the exact English option string used in the seed scripts. Unknown
// options fall back to the English text so a translation gap never drops an option.

const AR: Record<string, string> = {
  "True": "صواب",
  "False": "خطأ",
  "Class A": "الفئة أ",
  "Class B": "الفئة ب",
  "Class C": "الفئة ج",
  "Class D": "الفئة د",
  "Class F": "الفئة ف",
  "Water fire extinguisher": "طفاية مياه",
  "Carbon dioxide (CO₂) extinguisher": "طفاية ثاني أكسيد الكربون (CO₂)",
  "Dry chemical powder extinguisher": "طفاية مسحوق كيميائي جاف",
  "Foam fire extinguisher": "طفاية رغوة",
  "At least 4 feet": "4 أقدام على الأقل",
  "At least 6 feet": "6 أقدام على الأقل",
  "At least 8 feet": "8 أقدام على الأقل",
  "At least 10 feet": "10 أقدام على الأقل",
  "Safety pin": "دبوس الأمان",
  "Discharge hose": "خرطوم التفريغ",
  "Pressure gauge": "مقياس الضغط",
  "All of the above": "كل ما سبق",
  "Dry pipe system": "نظام الأنابيب الجافة",
  "Wet pipe system": "نظام الأنابيب المبللة",
  "Pre-action system": "نظام ما قبل الحركة",
  "Deluge system": "نظام الفيضان (الديلج)",
  "Electrical equipment": "المعدات الكهربائية",
  "Combustible metals": "المعادن القابلة للاشتعال",
  "Deep-seated carbonaceous fires": "الحرائق الكربونية العميقة",
  "Chemicals that contain their own oxygen": "المواد الكيميائية المحتوية على الأكسجين الخاص بها",
  "Cooling": "التبريد",
  "Blanketing (smothering)": "الخنق (التغطية)",
  "Removing fuel (starvation)": "إزالة الوقود (التجويع)",
  "Dilution": "التخفيف",
  "Liquid storage tanks and fuel transfer areas": "خزانات تخزين السوائل ومناطق نقل الوقود",
  "General office buildings": "مباني المكاتب العامة",
  "Computer and server rooms": "غرف الحاسوب والخوادم",
  "Residential apartments": "الشقق السكنية",
  "At the top of the flames": "عند قمة اللهب",
  "At the base of the flames": "عند قاعدة اللهب",
  "At the middle of the flames": "عند منتصف اللهب",
  "Above the fire": "فوق النار",
  "Class A and B only": "الفئتان أ و ب فقط",
  "Class B and C only": "الفئتان ب و ج فقط",
  "Class A, B, and C": "الفئات أ و ب و ج",
  "Class D only": "الفئة د فقط",
  "Fuel, heat, and oxygen": "الوقود والحرارة والأكسجين",
  "Fuel, water, and smoke": "الوقود والماء والدخان",
  "Heat, smoke, and gas": "الحرارة والدخان والغاز",
  "Oxygen, carbon dioxide, and fuel": "الأكسجين وثاني أكسيد الكربون والوقود",
  "Smothering (blanketing)": "الخنق (التغطية)",
  "Starvation (removing fuel)": "التجويع (إزالة الوقود)",
  "Chemical inhibition": "التثبيط الكيميائي",
  "Aim at the base of the flames": "وجّه نحو قاعدة اللهب",
  "Activate the fire alarm": "تفعيل إنذار الحريق",
  "Approach the fire": "الاقتراب من النار",
  "Assess the situation": "تقييم الوضع",
  "Oxygen concentration": "تركيز الأكسجين",
  "Flammability (LEL) of combustible gases": "قابلية الاشتعال (حد الانفجار الأدنى) للغازات القابلة للاشتعال",
  "Toxic gases such as CO and H₂S": "الغازات السامة مثل أول أكسيد الكربون وكبريتيد الهيدروجين",
  "Continue work with normal PPE": "مواصلة العمل بمعدات الوقاية العادية",
  "Breathing apparatus must be used": "يجب استخدام جهاز التنفس",
  "No work or confined space entry is allowed": "لا يُسمح بأي عمل أو دخول المكان المغلق",
  "Notify the fire watch only": "إخطار مراقب الحرائق فقط",
  "30-lb non-CO₂": "30 رطلاً غير ثاني أكسيد الكربون",
  "10-lb CO₂": "10 أرطال ثاني أكسيد الكربون",
  "5-lb dry powder": "5 أرطال مسحوق جاف",
  "20-lb foam": "20 رطلاً رغوة",
  "A hot work permit has been issued": "تم إصدار تصريح عمل ساخن",
  "The worker calls the supervisor": "استدعاء العامل للمشرف",
  "The standby man gives verbal permission": "إذن شفهي من رجل الاستعداد",
  "The space is evacuated for one hour": "إخلاء المكان لمدة ساعة",
  "Monitors activities inside and outside the confined space": "يراقب الأنشطة داخل وخارج المكان المغلق",
  "Maintains two-way communication with entrants": "يحافظ على اتصال ثنائي الاتجاه مع الداخلين",
  "Orders evacuation when an unsafe condition develops": "يأمر بالإخلاء عند حدوث حالة غير آمنة",
  "He must be trained and experienced in gas tests and gas monitoring": "يجب أن يكون مدرباً وذو خبرة في اختبارات ومراقبة الغاز",
  "He terminates an entry when job conditions change or an emergency arises": "يُنهي الدخول عند تغير ظروف العمل أو حدوث طارئ",
  "He documents safety requirements on the CSE permit": "يوثق متطلبات السلامة في تصريح دخول الأماكن المغلقة",
  "18": "18",
  "110": "110",
  "220": "220",
  "380": "380",
  "A simple dust mask": "قناع غبار بسيط",
  "Self-contained or supplied-air breathing apparatus": "جهاز تنفس مستقل أو مزود بالهواء",
  "A half-face filter respirator": "جهاز تنفس بنصف قناع بفلتر",
  "A paper surgical mask": "قناع جراحي ورقي",
  "6 months": "6 أشهر",
  "1 year": "سنة واحدة",
  "2 years": "سنتان",
  "5 years": "5 سنوات",
  "A full body harness with a retrieval line attached": "حزام جسم كامل مع حبل استرجاع مثبت",
  "A reflective vest only": "سترة عاكسة فقط",
  "Wrist bands for identification": "أشرطة معصم للتعريف",
  "A cotton coverall only": "زي قطنية كامل فقط",
  "An inert gas such as nitrogen": "غاز خامل مثل النيتروجين",
  "Compressed air": "هواء مضغوط",
  "Steam only": "بخار فقط",
  "Water flooding": "إغراق بالماء",
  "A system of rope signals": "نظام إشارات بالحبال",
  "Knocking on the wall": "الطرق على الجدار",
  "Smoke signals": "إشارات دخانية",
  "No communication is needed": "لا حاجة للاتصال",
  "A change in the person responsible for the work": "تغيير الشخص المسؤول عن العمل",
  "A significant break in work continuity": "انقطاع كبير في استمرارية العمل",
  "A significant change in the atmosphere or work performed": "تغيير جوهري في الجو أو العمل المنفذ",
  "Review the CSE plan and work permits": "مراجعة خطة الدخول وتصاريح العمل",
  "Understand hazards, precautions and emergency procedures": "فهم المخاطر والاحتياطات وإجراءات الطوارئ",
  "Know the effects of exposure to hazardous substances": "معرفة آثار التعرض للمواد الخطرة",
  "19.5% – 21%": "19.5% – 21%",
  "18% – 20%": "18% – 20%",
  "20.5% – 23.5%": "20.5% – 23.5%",
  "17% – 19.5%": "17% – 19.5%",
  "Storage tanks": "خزانات التخزين",
  "Manholes": "الفتحات (المنهولات)",
  "Boilers and steam generators": "الغلايات ومولدات البخار",
  "The entrant": "الداخل",
  "The standby man (attendant)": "رجل الاستعداد (المراقب)",
  "The rescue team": "فريق الإنقاذ",
  "The gas tester": "مختبر الغاز",
  "Leave the entry point without relief": "مغادرة نقطة الدخول دون إبدال",
  "Enter the confined space": "دخول المكان المغلق",
  "Perform other duties that interfere with standby duties": "أداء مهام أخرى تتعارض مع مهام الاستعداد",
  "Contains or could contain a hazardous atmosphere": "يحتوي أو قد يحتوي على جو خطير",
  "Has the potential for engulfing the entrant": "يحتمل احتواء (ابتلاع) الداخل",
  "Has an internal configuration where the entrant could be trapped or asphyxiated": "تكوين داخلي قد يُحتجز فيه الداخل أو يختنق",
  "two-way communication": "اتصال ثنائي الاتجاه",
  "written notes": "ملاحظات مكتوبة",
  "one-way voice contact": "اتصال صوتي أحادي الاتجاه",
  "visual signals only": "إشارات بصرية فقط",
  "20,000 °C": "20,000 درجة مئوية",
  "5,000 °C": "5,000 درجة مئوية",
  "50,000 °C": "50,000 درجة مئوية",
  "1,000 °C": "1,000 درجة مئوية",
  "Qualified personnel wearing appropriate PPE": "الأفراد المؤهلون مرتدين معدات الوقاية المناسبة",
  "Any worker with a valid work permit": "أي عامل لديه تصريح عمل ساري",
  "Visitors with supervision": "الزوار تحت الإشراف",
  "The site nurse": "ممرض الموقع",
  "Improper grounding of equipment and circuitry": "تأريض غير صحيح للمعدات والدوائر",
  "Using LED lighting": "استخدام إضاءة LED",
  "Installing too many outlets": "تركيب مخارج كهربائية كثيرة جداً",
  "Using aluminum wire": "استخدام أسلاك ألمنيوم",
  "2 consecutive calendar days": "يومان تقويميان متتاليان",
  "10 consecutive calendar days": "10 أيام تقويمية متتالية",
  "7 consecutive calendar days": "7 أيام تقويمية متتالية",
  "1 calendar day": "يوم تقويمي واحد",
  "400 VAC": "400 فولت تيار متناوب",
  "110 VAC": "110 فولت تيار متناوب",
  "1000 VAC": "1000 فولت تيار متناوب",
  "220 VAC": "220 فولت تيار متناوب",
  "Permit Receiver": "مستلم التصريح",
  "The fire watcher": "مراقب الحرائق",
  "The site visitor": "زائر الموقع",
  "The safety equipment supplier": "مورد معدات السلامة",
  "The type of permits/certificates to be issued and whether a JSA is required": "نوع التصاريح/الشهادات التي سيتم إصدارها وما إذا كان تحليل سلامة العمل مطلوباً",
  "The salary level of the workers": "مستوى رواتب العمال",
  "The color of the barricade tape": "لون شريط الحواجز",
  "The number of workers on site": "عدد العمال في الموقع",
  "Without considering existing controls": "دون النظر في الضوابط الحالية",
  "After all controls have been implemented": "بعد تطبيق جميع الضوابط",
  "Only considering the financial cost": "بالنظر إلى التكلفة المالية فقط",
  "After the residual risk is determined": "بعد تحديد الخطر المتبقي",
  "Yellow": "الأصفر",
  "Safety red": "الأحمر للسلامة",
  "Safety blue": "الأزرق للسلامة",
  "Orange": "البرتقالي",
  "Job Safety Analysis": "تحليل سلامة العمل (JSA)",
  "Joint Safety Audit": "تدقيق السلامة المشترك",
  "Job Service Agreement": "اتفاقية خدمة العمل",
  "Junior Safety Assessor": "مقيّم السلامة المبتدئ",
  "Hot Work Permit": "تصريح العمل الساخن",
  "Electrical Work Permit": "تصريح العمل الكهربائي",
  "Sanction for Test (SFT)": "تصريح الإذن بالاختبار (SFT)",
  "Parking Permit": "تصريح مواقف السيارات",
  "Shuffle your feet, keeping them touching at all times": "حرّك قدميك بخطوات قصيرة مع بقائهما ملتصقتين طوال الوقت",
  "Run quickly away from the area": "اركض بسرعة بعيداً عن المنطقة",
  "Jump with both feet together": "اقفز بكلتا القدمين معاً",
  "Walk normally with long steps": "امشِ بشكل طبيعي بخطوات طويلة",
  "1.2 cal/cm²": "1.2 كالوري/سم²",
  "5 J/cm²": "5 جول/سم²",
  "0.5 cal/cm²": "0.5 كالوري/سم²",
  "2.0 cal/cm²": "2.0 كالوري/سم²",
  "Administrative buildings in non-restricted areas": "المباني الإدارية في المناطق غير المقيّدة",
  "All offices including work areas": "جميع المكاتب بما فيها مناطق العمل",
  "Substations and switchyards": "المحطات الفرعية وساحات التبديل",
  "Any area inside the arc flash boundary": "أي منطقة داخل حدود وميض القوس",
  "Extreme, High, Moderate or Low": "شديد أو مرتفع أو متوسط أو منخفض",
  "Critical, Severe or Minor": "حرج أو شديد أو طفيف",
  "High, Medium or Low": "مرتفع أو متوسط أو منخفض",
  "Level 1 to Level 10": "من المستوى 1 إلى المستوى 10",
  "Hazard identification": "تحديد المخاطر",
  "Establishing the scope": "تحديد النطاق",
  "Treating the risks": "معالجة المخاطر",
  "Communication and consultation": "التواصل والتشاور",
  "120 kg": "120 كجم",
  "80 kg": "80 كجم",
  "150 kg": "150 كجم",
  "200 kg": "200 كجم",
  "At least one connection point is maintained at all times": "الحفاظ على نقطة توصيل واحدة على الأقل في جميع الأوقات",
  "Two workers can be secured simultaneously": "يمكن تأمين عاملين في نفس الوقت",
  "The lanyard can support twice the load": "يمكن للحبل أن يتحمل ضعف الحمولة",
  "The worker can work without a harness": "يمكن للعامل العمل دون حزام أمان",
  "5": "5",
  "2": "2",
  "3": "3",
  "10": "10",
  "Lifting a load of 10 tons or more": "رفع حمولة 10 أطنان أو أكثر",
  "Lifting a load of less than 1 ton": "رفع حمولة أقل من طن واحد",
  "Moving a load within a warehouse using a forklift": "نقل حمولة داخل مستودع باستخدام رافعة شوكية",
  "Lifting with hand chain blocks": "الرفع بالرافعات اليدوية ذات السلسلة",
  "32 km/h (20 mph)": "32 كم/ساعة (20 ميل/ساعة)",
  "50 km/h (31 mph)": "50 كم/ساعة (31 ميل/ساعة)",
  "60 km/h (37 mph)": "60 كم/ساعة (37 ميل/ساعة)",
  "25 km/h (15 mph)": "25 كم/ساعة (15 ميل/ساعة)",
  "10 mA": "10 مللي أمبير",
  "30 mA": "30 مللي أمبير",
  "100 mA": "100 مللي أمبير",
  "500 mA": "500 مللي أمبير",
  "Areas where specific commissioning activities are taking place": "المناطق التي تجري فيها أنشطة تشغيل محددة",
  "Hazards to people, plant and the environment": "مخاطر على الأشخاص والمعدات والبيئة",
  "Work areas requiring supervisor authorization": "مناطق العمل التي تتطلب إذن المشرف",
  "Excavation boundaries": "حدود الحفريات",
  "A retractable spring-loaded guard that allows only the working part of the blade to be exposed": "واقٍ قابل للسحب بمزلاج زنبركي يسمح بظهور الجزء العامل من الشفرة فقط",
  "A fixed guard covering the whole blade": "واقٍ ثابت يغطي الشفرة بالكامل",
  "A trigger lock to hold the switch on": "قفل زناد لتثبيت المفتاح في وضع التشغيل",
  "A homemade guard made on site": "واقٍ مصنوع محلياً في الموقع",
  "Job Safe Procedure": "إجراءات العمل الآمنة",
  "Job Safety Program": "برنامج سلامة العمل",
  "Joint Safety Permit": "تصريح السلامة المشترك",
  "Job Service Procedure": "إجراء خدمة العمل",
  "Likelihood (probability)": "الاحتمالية",
  "Cost": "التكلفة",
  "Duration of the task": "مدة المهمة",
  "Number of workers": "عدد العمال",
  "Anchorage, Body Support, Connection": "نقطة التثبيت، دعم الجسم، أداة التوصيل",
  "Alloy, Belt, Clamp": "السبيكة، الحزام، المشبك",
  "Anchor, Buckle, Cable": "المرساة، الإبزيم، الكابل",
  "Angle, Brace, Clasp": "الزاوية، الدعامة، المثبت",
  "30 degrees": "30 درجة",
  "45 degrees": "45 درجة",
  "20 degrees": "20 درجة",
  "15 degrees": "15 درجة",
  "Red": "الأحمر",
  "Green": "الأخضر",
  "Blue": "الأزرق",
  "Personnel authorized to fix or remove the hazard": "الأفراد المصرح لهم بإصلاح الخطر أو إزالته",
  "Any visitor with a safety briefing": "أي زائر حصل على جلسة تعريف بالسلامة",
  "ISMS (Integrated Safety Management System)": "نظام إدارة السلامة المتكامل (ISMS)",
  "OSHA": "أوشا (OSHA)",
  "ISO 9001": "آيزو 9001",
  "MSDS": "صحيفة بيانات سلامة المواد (MSDS)",
  "The human response to physical loads": "استجابة الإنسان للأحمال الفيزيائية",
  "The mind's treatment of perception and memory": "معالجة العقل للإدراك والذاكرة",
  "Improving social systems and teamwork": "تحسين الأنظمة الاجتماعية والعمل الجماعي",
  "Marketing and sales strategies": "استراتيجيات التسويق والمبيعات",
  "Improving social systems such as work schedules, employee satisfaction and teamwork": "تحسين الأنظمة الاجتماعية مثل جداول العمل ورضا الموظفين والعمل الجماعي",
  "Perception and attention of the mind": "إدراك العقل وانتباهه",
  "Designing machines and equipment": "تصميم الآلات والمعدات",
  "Fuel": "الوقود",
  "Oxygen": "الأكسجين",
  "Heat": "الحرارة",
  "Smoke": "الدخان",
  "Flammable liquids and gases such as petroleum, oils and acetylene": "السوائل والغازات القابلة للاشتعال مثل البترول والزيوت والأسيتيلين",
  "Normal dry flammable materials such as wood and paper": "المواد الجافة القابلة للاشتعال العادية مثل الخشب والورق",
  "Light metals such as aluminum and magnesium": "المعادن الخفيفة مثل الألمنيوم والمغنيسيوم",
  "Vegetable oil in kitchens": "الزيوت النباتية في المطابخ",
  "Burns and heat": "الحروق والحرارة",
  "Chemicals": "المواد الكيميائية",
  "Electricity": "الكهرباء",
  "Abrasion and infection": "السحجات والعدوى",
  "Disconnect the electrical current and remove the person using an insulating material": "افصل التيار الكهربائي وأبعد الشخص باستخدام مادة عازلة",
  "Touch the injured person directly to pull him away": "لمس المصاب مباشرة لسحبه بعيداً",
  "Pour water on the injured person": "صب الماء على المصاب",
  "Call the police before doing anything": "الاتصال بالشرطة قبل القيام بأي شيء",
  "3000 to 100,000 ohms": "من 3000 إلى 100,000 أوم",
  "400 to 600 ohms": "من 400 إلى 600 أوم",
  "About 100 ohms": "حوالي 100 أوم",
  "About 1000 ohms": "حوالي 1000 أوم",
  "Heart disorder that may cause death": "اضطراب في القلب قد يسبب الوفاة",
  "A feeling of shock without pain": "إحساس بالصدمة دون ألم",
  "No effect on the body": "لا تأثير على الجسم",
  "Only mild discomfort": "انزعاج خفيف فقط",
  "28 inches": "28 بوصة",
  "18 inches": "18 بوصة",
  "12 inches": "12 بوصة",
  "36 inches": "36 بوصة",
  "45–60 cm": "45–60 سم",
  "10–20 cm": "10–20 سم",
  "100–120 cm": "100–120 سم",
  "150 cm": "150 سم",
  "The science that seeks to protect people from dangers and prevent loss of life and property": "العلم الذي يهدف إلى حماية الناس من الأخطار ومنع فقدان الأرواح والممتلكات",
  "The science of increasing production speed": "علم زيادة سرعة الإنتاج",
  "The rules for using office machines only": "قواعد استخدام الآلات المكتبية فقط",
  "A procedure followed after an accident only": "إجراء يُتبع بعد الحوادث فقط",
  "Protecting human safety and health from work risks by providing a safe work environment": "حماية سلامة وصحة الإنسان من مخاطر العمل عبر توفير بيئة عمل آمنة",
  "Increasing the number of workers in the workplace": "زيادة عدد العمال في مكان العمل",
  "Designing office furniture only": "تصميم الأثاث المكتبي فقط",
  "Reducing the cost of insurance premiums": "خفض تكلفة أقساط التأمين",
  "Plan, Do, Check, Act": "خطط، نفذ، تحقق، صحح",
  "Plan, Act, Do, Check": "خطط، صحح، نفذ، تحقق",
  "Do, Plan, Check, Act": "نفذ، خطط، تحقق، صحح",
  "Check, Do, Act, Plan": "تحقق، نفذ، صحح، خطط",
  "A": "أ",
  "B": "ب",
  "C": "ج",
  "D": "د",
  "First aid": "الإسعافات الأولية",
  "Occupational therapy": "العلاج الوظيفي",
  "Preventive medicine": "الطب الوقائي",
  "Physical rehabilitation": "إعادة التأهيل البدني",
  "Elimination, Substitution, Engineering, Administrative, PPE": "الإزالة، الاستبدال، الضوابط الهندسية، الضوابط الإدارية، معدات الحماية الشخصية",
  "PPE, Administrative, Engineering, Substitution, Elimination": "معدات الحماية، إدارية، هندسية، استبدال، إزالة",
  "Substitution, Elimination, Administrative, Engineering, PPE": "استبدال، إزالة، إدارية، هندسية، معدات حماية",
  "Engineering, Elimination, PPE, Substitution, Administrative": "هندسية، إزالة، معدات حماية، استبدال، إدارية",
  "JSA": "تحليل سلامة العمل (JSA)",
  "HAZID": "تحديد المخاطر (HAZID)",
  "QRA": "تقييم المخاطر الكمي (QRA)",
  "LOPA": "تحليل طبقة الحماية (LOPA)",
  "Only causes and consequences": "الأسباب والعواقب فقط",
  "Hazards, their causes (threats), consequences, and existing safeguards": "المخاطر وأسبابها (التهديدات) وعواقبها والضمانات القائمة",
  "Only consequences and safeguards": "العواقب والضمانات فقط",
  "Only probability and severity": "الاحتمالية والشدة فقط",
  "Reduce the consequence of the hazard": "تقليل عواقب الخطر",
  "Reduce the likelihood of the cause leading to the hazard": "تقليل احتمالية السبب المؤدي إلى الخطر",
  "Transfer the risk to another party": "نقل المخاطر إلى طرف آخر",
  "Increase the hazard severity": "زيادة شدة الخطر",
  "Reduce the likelihood of the cause": "تقليل احتمالية السبب",
  "Eliminate the hazard completely": "إزالة الخطر بالكامل",
  "Delay the work activity": "تأجيل نشاط العمل",
  "Qualitative": "نوعي",
  "Semi-quantitative": "شبه كمي",
  "Quantitative": "كمي",
  "Deterministic": "حتمي",
  "Subjective": "ذاتي",
  "The likelihood of the causes and the impact of the hazard without considering safeguards": "احتمالية الأسباب وتأثير الخطر دون النظر في الضمانات",
  "Only the existing safeguards": "الضمانات القائمة فقط",
  "The residual risk after controls": "الخطر المتبقي بعد الضوابط",
  "The financial cost of the incident": "التكلفة المالية للحادث",
  "At the point of operation, communicated to all employees": "في نقطة التشغيل وإبلاغ جميع الموظفين به",
  "In a locked filing cabinet": "في خزانة ملفات مقفلة",
  "At the company headquarters": "في مقر الشركة",
  "Only with the external auditor": "مع المدقق الخارجي فقط",
  "Low": "منخفض",
  "Medium": "متوسط",
  "Very Low": "منخفض جداً",
  "Negligible": "ضئيل (لا يُذكر)",
  "Finance": "التمويل",
  "HSE field": "مجال الصحة والسلامة والبيئة (HSE)",
  "Procurement": "المشتريات",
  "Public relations": "العلاقات العامة",
  "Installing machine guards and ventilation systems": "تركيب واقيات الآلات وأنظمة التهوية",
  "Job rotation and safety signs": "تناوب الوظائف ولافتات السلامة",
  "Wearing gloves and hard hats": "ارتداء القفازات والخوذ",
  "Writing standard operating procedures": "كتابة إجراءات التشغيل القياسية",
  "Guards on moving parts": "واقيات على الأجزاء المتحركة",
  "Procedures, training, and job rotation": "الإجراءات والتدريب وتناوب الوظائف",
  "Secondary containment": "الاحتواء الثانوي",
  "Pressure safety valves": "صمامات تخفيف الضغط",
  "Empirical": "تجريبي",
  "Roles and responsibilities (Responsible, Accountable, Consulted, Informed)": "الأدوار والمسؤوليات (مسؤول، محاسب، مستشار، مُطّلع)",
  "The cost of risk controls": "تكلفة ضوابط المخاطر",
  "The order of risk treatment": "ترتيب معالجة المخاطر",
  "The hierarchy of controls": "التسلسل الهرمي للضوابط",
  "The chance of an accident": "احتمالية وقوع حادث",
  "A condition with the potential for harm": "حالة تحمل احتمالية التسبب بالضرر",
  "A past incident report": "تقرير حادث سابق",
  "The severity of an injury": "شدة الإصابة",
  "Personal Protective Equipment": "معدات الحماية الشخصية",
  "Elimination": "الإزالة",
  "Administrative controls": "الضوابط الإدارية",
  "Engineering controls": "الضوابط الهندسية",
  "In the office": "في المكتب",
  "At the point of operation": "في نقطة التشغيل",
  "With the safety committee": "مع لجنة السلامة",
  "At the manager's desk": "على مكتب المدير",
  "Substitution": "الاستبدال",
  "Personal Protective Equipment (PPE)": "معدات الحماية الشخصية (PPE)",
  "A wet floor": "أرضية مبللة",
  "Exposure to electricity": "التعرض للكهرباء",
  "Working at height": "العمل على المرتفعات",
  "High or Extreme": "مرتفع أو شديد",
  "Medium or Low": "متوسط أو منخفض",
  "Extreme only": "شديد فقط",
  "High only": "مرتفع فقط",
};

export function translateOptions(options: string[]): string[] {
  return options.map((o) => AR[o.trim()] ?? o);
}
