// Shared Arabic translation of answer options for the seeded question banks.
// Keyed by the exact English option string used in the seed scripts. Unknown
// options fall back to the English text so a translation gap never drops an option.

const AR: Record<string, string> = {
  "True": "صواب",
  "False": "خطأ",
  "Class A": "الفئة أ",
  "Class B": "الفئة ب",
  "Class C": "الفئة ج",
  "Class D": "الفئة د",
  "Class F": "الفئة ف",
  "Water fire extinguisher": "طفاية مياه",
  "Carbon dioxide (CO₂) extinguisher": "طفاية ثاني أكسيد الكربون (CO₂)",
  "Dry chemical powder extinguisher": "طفاية مسحوق كيميائي جاف",
  "Foam fire extinguisher": "طفاية رغوة",
  "At least 4 feet": "4 أقدام على الأقل",
  "At least 6 feet": "6 أقدام على الأقل",
  "At least 8 feet": "8 أقدام على الأقل",
  "At least 10 feet": "10 أقدام على الأقل",
  "Safety pin": "دبوس الأمان",
  "Discharge hose": "خرطوم التفريغ",
  "Pressure gauge": "مقياس الضغط",
  "All of the above": "كل ما سبق",
  "Dry pipe system": "نظام الأنابيب الجافة",
  "Wet pipe system": "نظام الأنابيب المبللة",
  "Pre-action system": "نظام ما قبل الحركة",
  "Deluge system": "نظام الفيضان (الديلج)",
  "Electrical equipment": "المعدات الكهربائية",
  "Combustible metals": "المعادن القابلة للاشتعال",
  "Deep-seated carbonaceous fires": "الحرائق الكربونية العميقة",
  "Chemicals that contain their own oxygen": "المواد الكيميائية المحتوية على الأكسجين الخاص بها",
  "Cooling": "التبريد",
  "Blanketing (smothering)": "الخنق (التغطية)",
  "Removing fuel (starvation)": "إزالة الوقود (التجويع)",
  "Dilution": "التخفيف",
  "Liquid storage tanks and fuel transfer areas": "خزانات تخزين السوائل ومناطق نقل الوقود",
  "General office buildings": "مباني المكاتب العامة",
  "Computer and server rooms": "غرف الحاسوب والخوادم",
  "Residential apartments": "الشقق السكنية",
  "At the top of the flames": "عند قمة اللهب",
  "At the base of the flames": "عند قاعدة اللهب",
  "At the middle of the flames": "عند منتصف اللهب",
  "Above the fire": "فوق النار",
  "Class A and B only": "الفئتان أ و ب فقط",
  "Class B and C only": "الفئتان ب و ج فقط",
  "Class A, B, and C": "الفئات أ و ب و ج",
  "Class D only": "الفئة د فقط",
  "Fuel, heat, and oxygen": "الوقود والحرارة والأكسجين",
  "Fuel, water, and smoke": "الوقود والماء والدخان",
  "Heat, smoke, and gas": "الحرارة والدخان والغاز",
  "Oxygen, carbon dioxide, and fuel": "الأكسجين وثاني أكسيد الكربون والوقود",
  "Smothering (blanketing)": "الخنق (التغطية)",
  "Starvation (removing fuel)": "التجويع (إزالة الوقود)",
  "Chemical inhibition": "التثبيط الكيميائي",
  "Aim at the base of the flames": "وجّه نحو قاعدة اللهب",
  "Activate the fire alarm": "تفعيل إنذار الحريق",
  "Approach the fire": "الاقتراب من النار",
  "Assess the situation": "تقييم الوضع",
  "Oxygen concentration": "تركيز الأكسجين",
  "Flammability (LEL) of combustible gases": "قابلية الاشتعال (حد الانفجار الأدنى) للغازات القابلة للاشتعال",
  "Toxic gases such as CO and H₂S": "الغازات السامة مثل أول أكسيد الكربون وكبريتيد الهيدروجين",
  "Continue work with normal PPE": "مواصلة العمل بمعدات الوقاية العادية",
  "Breathing apparatus must be used": "يجب استخدام جهاز التنفس",
  "No work or confined space entry is allowed": "لا يُسمح بأي عمل أو دخول المكان المغلق",
  "Notify the fire watch only": "إخطار مراقب الحرائق فقط",
  "30-lb non-CO₂": "30 رطلاً غير ثاني أكسيد الكربون",
  "10-lb CO₂": "10 أرطال ثاني أكسيد الكربون",
  "5-lb dry powder": "5 أرطال مسحوق جاف",
  "20-lb foam": "20 رطلاً رغوة",
  "A hot work permit has been issued": "تم إصدار تصريح عمل ساخن",
  "The worker calls the supervisor": "استدعاء العامل للمشرف",
  "The standby man gives verbal permission": "إذن شفهي من رجل الاستعداد",
  "The space is evacuated for one hour": "إخلاء المكان لمدة ساعة",
  "Monitors activities inside and outside the confined space": "يراقب الأنشطة داخل وخارج المكان المغلق",
  "Maintains two-way communication with entrants": "يحافظ على اتصال ثنائي الاتجاه مع الداخلين",
  "Orders evacuation when an unsafe condition develops": "يأمر بالإخلاء عند حدوث حالة غير آمنة",
  "He must be trained and experienced in gas tests and gas monitoring": "يجب أن يكون مدرباً وذو خبرة في اختبارات ومراقبة الغاز",
  "He terminates an entry when job conditions change or an emergency arises": "يُنهي الدخول عند تغير ظروف العمل أو حدوث طارئ",
  "He documents safety requirements on the CSE permit": "يوثق متطلبات السلامة في تصريح دخول الأماكن المغلقة",
  "18": "18",
  "110": "110",
  "220": "220",
  "380": "380",
  "A simple dust mask": "قناع غبار بسيط",
  "Self-contained or supplied-air breathing apparatus": "جهاز تنفس مستقل أو مزود بالهواء",
  "A half-face filter respirator": "جهاز تنفس بنصف قناع بفلتر",
  "A paper surgical mask": "قناع جراحي ورقي",
  "6 months": "6 أشهر",
  "1 year": "سنة واحدة",
  "2 years": "سنتان",
  "5 years": "5 سنوات",
  "A full body harness with a retrieval line attached": "حزام جسم كامل مع حبل استرجاع مثبت",
  "A reflective vest only": "سترة عاكسة فقط",
  "Wrist bands for identification": "أشرطة معصم للتعريف",
  "A cotton coverall only": "زي قطنية كامل فقط",
  "An inert gas such as nitrogen": "غاز خامل مثل النيتروجين",
  "Compressed air": "هواء مضغوط",
  "Steam only": "بخار فقط",
  "Water flooding": "إغراق بالماء",
  "A system of rope signals": "نظام إشارات بالحبال",
  "Knocking on the wall": "الطرق على الجدار",
  "Smoke signals": "إشارات دخانية",
  "No communication is needed": "لا حاجة للاتصال",
  "A change in the person responsible for the work": "تغيير الشخص المسؤول عن العمل",
  "A significant break in work continuity": "انقطاع كبير في استمرارية العمل",
  "A significant change in the atmosphere or work performed": "تغيير جوهري في الجو أو العمل المنفذ",
  "Review the CSE plan and work permits": "مراجعة خطة الدخول وتصاريح العمل",
  "Understand hazards, precautions and emergency procedures": "فهم المخاطر والاحتياطات وإجراءات الطوارئ",
  "Know the effects of exposure to hazardous substances": "معرفة آثار التعرض للمواد الخطرة",
  "19.5% – 21%": "19.5% – 21%",
  "18% – 20%": "18% – 20%",
  "20.5% – 23.5%": "20.5% – 23.5%",
  "17% – 19.5%": "17% – 19.5%",
  "Storage tanks": "خزانات التخزين",
  "Manholes": "الفتحات (المنهولات)",
  "Boilers and steam generators": "الغلايات ومولدات البخار",
  "The entrant": "الداخل",
  "The standby man (attendant)": "رجل الاستعداد (المراقب)",
  "The rescue team": "فريق الإنقاذ",
  "The gas tester": "مختبر الغاز",
  "Leave the entry point without relief": "مغادرة نقطة الدخول دون إبدال",
  "Enter the confined space": "دخول المكان المغلق",
  "Perform other duties that interfere with standby duties": "أداء مهام أخرى تتعارض مع مهام الاستعداد",
  "Contains or could contain a hazardous atmosphere": "يحتوي أو قد يحتوي على جو خطير",
  "Has the potential for engulfing the entrant": "يحتمل احتواء (ابتلاع) الداخل",
  "Has an internal configuration where the entrant could be trapped or asphyxiated": "تكوين داخلي قد يُحتجز فيه الداخل أو يختنق",
  "two-way communication": "اتصال ثنائي الاتجاه",
  "written notes": "ملاحظات مكتوبة",
  "one-way voice contact": "اتصال صوتي أحادي الاتجاه",
  "visual signals only": "إشارات بصرية فقط",
  "20,000 °C": "20,000 درجة مئوية",
  "5,000 °C": "5,000 درجة مئوية",
  "50,000 °C": "50,000 درجة مئوية",
  "1,000 °C": "1,000 درجة مئوية",
  "Qualified personnel wearing appropriate PPE": "الأفراد المؤهلون مرتدين معدات الوقاية المناسبة",
  "Any worker with a valid work permit": "أي عامل لديه تصريح عمل ساري",
  "Visitors with supervision": "الزوار تحت الإشراف",
  "The site nurse": "ممرض الموقع",
  "Improper grounding of equipment and circuitry": "تأريض غير صحيح للمعدات والدوائر",
  "Using LED lighting": "استخدام إضاءة LED",
  "Installing too many outlets": "تركيب مخارج كهربائية كثيرة جداً",
  "Using aluminum wire": "استخدام أسلاك ألمنيوم",
  "2 consecutive calendar days": "يومان تقويميان متتاليان",
  "10 consecutive calendar days": "10 أيام تقويمية متتالية",
  "7 consecutive calendar days": "7 أيام تقويمية متتالية",
  "1 calendar day": "يوم تقويمي واحد",
  "400 VAC": "400 فولت تيار متناوب",
  "110 VAC": "110 فولت تيار متناوب",
  "1000 VAC": "1000 فولت تيار متناوب",
  "220 VAC": "220 فولت تيار متناوب",
  "Permit Receiver": "مستلم التصريح",
  "The fire watcher": "مراقب الحرائق",
  "The site visitor": "زائر الموقع",
  "The safety equipment supplier": "مورد معدات السلامة",
  "The type of permits/certificates to be issued and whether a JSA is required": "نوع التصاريح/الشهادات التي سيتم إصدارها وما إذا كان تحليل سلامة العمل مطلوباً",
  "The salary level of the workers": "مستوى رواتب العمال",
  "The color of the barricade tape": "لون شريط الحواجز",
  "The number of workers on site": "عدد العمال في الموقع",
  "Without considering existing controls": "دون النظر في الضوابط الحالية",
  "After all controls have been implemented": "بعد تطبيق جميع الضوابط",
  "Only considering the financial cost": "بالنظر إلى التكلفة المالية فقط",
  "After the residual risk is determined": "بعد تحديد الخطر المتبقي",
  "Yellow": "الأصفر",
  "Safety red": "الأحمر للسلامة",
  "Safety blue": "الأزرق للسلامة",
  "Orange": "البرتقالي",
  "Job Safety Analysis": "تحليل سلامة العمل (JSA)",
  "Joint Safety Audit": "تدقيق السلامة المشترك",
  "Job Service Agreement": "اتفاقية خدمة العمل",
  "Junior Safety Assessor": "مقيّم السلامة المبتدئ",
  "Hot Work Permit": "تصريح العمل الساخن",
  "Electrical Work Permit": "تصريح العمل الكهربائي",
  "Sanction for Test (SFT)": "تصريح الإذن بالاختبار (SFT)",
  "Parking Permit": "تصريح مواقف السيارات",
  "Shuffle your feet, keeping them touching at all times": "حرّك قدميك بخطوات قصيرة مع بقائهما ملتصقتين طوال الوقت",
  "Run quickly away from the area": "اركض بسرعة بعيداً عن المنطقة",
  "Jump with both feet together": "اقفز بكلتا القدمين معاً",
  "Walk normally with long steps": "امشِ بشكل طبيعي بخطوات طويلة",
  "1.2 cal/cm²": "1.2 كالوري/سم²",
  "5 J/cm²": "5 جول/سم²",
  "0.5 cal/cm²": "0.5 كالوري/سم²",
  "2.0 cal/cm²": "2.0 كالوري/سم²",
  "Administrative buildings in non-restricted areas": "المباني الإدارية في المناطق غير المقيّدة",
  "All offices including work areas": "جميع المكاتب بما فيها مناطق العمل",
  "Substations and switchyards": "المحطات الفرعية وساحات التبديل",
  "Any area inside the arc flash boundary": "أي منطقة داخل حدود وميض القوس",
  "Extreme, High, Moderate or Low": "شديد أو مرتفع أو متوسط أو منخفض",
  "Critical, Severe or Minor": "حرج أو شديد أو طفيف",
  "High, Medium or Low": "مرتفع أو متوسط أو منخفض",
  "Level 1 to Level 10": "من المستوى 1 إلى المستوى 10",
  "Hazard identification": "تحديد المخاطر",
  "Establishing the scope": "تحديد النطاق",
  "Treating the risks": "معالجة المخاطر",
  "Communication and consultation": "التواصل والتشاور",
  "120 kg": "120 كجم",
  "80 kg": "80 كجم",
  "150 kg": "150 كجم",
  "200 kg": "200 كجم",
  "At least one connection point is maintained at all times": "الحفاظ على نقطة توصيل واحدة على الأقل في جميع الأوقات",
  "Two workers can be secured simultaneously": "يمكن تأمين عاملين في نفس الوقت",
  "The lanyard can support twice the load": "يمكن للحبل أن يتحمل ضعف الحمولة",
  "The worker can work without a harness": "يمكن للعامل العمل دون حزام أمان",
  "5": "5",
  "2": "2",
  "3": "3",
  "10": "10",
  "Lifting a load of 10 tons or more": "رفع حمولة 10 أطنان أو أكثر",
  "Lifting a load of less than 1 ton": "رفع حمولة أقل من طن واحد",
  "Moving a load within a warehouse using a forklift": "نقل حمولة داخل مستودع باستخدام رافعة شوكية",
  "Lifting with hand chain blocks": "الرفع بالرافعات اليدوية ذات السلسلة",
  "32 km/h (20 mph)": "32 كم/ساعة (20 ميل/ساعة)",
  "50 km/h (31 mph)": "50 كم/ساعة (31 ميل/ساعة)",
  "60 km/h (37 mph)": "60 كم/ساعة (37 ميل/ساعة)",
  "25 km/h (15 mph)": "25 كم/ساعة (15 ميل/ساعة)",
  "10 mA": "10 مللي أمبير",
  "30 mA": "30 مللي أمبير",
  "100 mA": "100 مللي أمبير",
  "500 mA": "500 مللي أمبير",
  "Areas where specific commissioning activities are taking place": "المناطق التي تجري فيها أنشطة تشغيل محددة",
  "Hazards to people, plant and the environment": "مخاطر على الأشخاص والمعدات والبيئة",
  "Work areas requiring supervisor authorization": "مناطق العمل التي تتطلب إذن المشرف",
  "Excavation boundaries": "حدود الحفريات",
  "A retractable spring-loaded guard that allows only the working part of the blade to be exposed": "واقٍ قابل للسحب بمزلاج زنبركي يسمح بظهور الجزء العامل من الشفرة فقط",
  "A fixed guard covering the whole blade": "واقٍ ثابت يغطي الشفرة بالكامل",
  "A trigger lock to hold the switch on": "قفل زناد لتثبيت المفتاح في وضع التشغيل",
  "A homemade guard made on site": "واقٍ مصنوع محلياً في الموقع",
  "Job Safe Procedure": "إجراءات العمل الآمنة",
  "Job Safety Program": "برنامج سلامة العمل",
  "Joint Safety Permit": "تصريح السلامة المشترك",
  "Job Service Procedure": "إجراء خدمة العمل",
  "Likelihood (probability)": "الاحتمالية",
  "Cost": "التكلفة",
  "Duration of the task": "مدة المهمة",
  "Number of workers": "عدد العمال",
  "Anchorage, Body Support, Connection": "نقطة التثبيت، دعم الجسم، أداة التوصيل",
  "Alloy, Belt, Clamp": "السبيكة، الحزام، المشبك",
  "Anchor, Buckle, Cable": "المرساة، الإبزيم، الكابل",
  "Angle, Brace, Clasp": "الزاوية، الدعامة، المثبت",
  "30 degrees": "30 درجة",
  "45 degrees": "45 درجة",
  "20 degrees": "20 درجة",
  "15 degrees": "15 درجة",
  "Red": "الأحمر",
  "Green": "الأخضر",
  "Blue": "الأزرق",
  "Personnel authorized to fix or remove the hazard": "الأفراد المصرح لهم بإصلاح الخطر أو إزالته",
  "Any visitor with a safety briefing": "أي زائر حصل على جلسة تعريف بالسلامة",
  "ISMS (Integrated Safety Management System)": "نظام إدارة السلامة المتكامل (ISMS)",
  "OSHA": "أوشا (OSHA)",
  "ISO 9001": "آيزو 9001",
  "MSDS": "صحيفة بيانات سلامة المواد (MSDS)",
  "The human response to physical loads": "استجابة الإنسان للأحمال الفيزيائية",
  "The mind's treatment of perception and memory": "معالجة العقل للإدراك والذاكرة",
  "Improving social systems and teamwork": "تحسين الأنظمة الاجتماعية والعمل الجماعي",
  "Marketing and sales strategies": "استراتيجيات التسويق والمبيعات",
  "Improving social systems such as work schedules, employee satisfaction and teamwork": "تحسين الأنظمة الاجتماعية مثل جداول العمل ورضا الموظفين والعمل الجماعي",
  "Perception and attention of the mind": "إدراك العقل وانتباهه",
  "Designing machines and equipment": "تصميم الآلات والمعدات",
  "Fuel": "الوقود",
  "Oxygen": "الأكسجين",
  "Heat": "الحرارة",
  "Smoke": "الدخان",
  "Flammable liquids and gases such as petroleum, oils and acetylene": "السوائل والغازات القابلة للاشتعال مثل البترول والزيوت والأسيتيلين",
  "Normal dry flammable materials such as wood and paper": "المواد الجافة القابلة للاشتعال العادية مثل الخشب والورق",
  "Light metals such as aluminum and magnesium": "المعادن الخفيفة مثل الألمنيوم والمغنيسيوم",
  "Vegetable oil in kitchens": "الزيوت النباتية في المطابخ",
  "Burns and heat": "الحروق والحرارة",
  "Chemicals": "المواد الكيميائية",
  "Electricity": "الكهرباء",
  "Abrasion and infection": "السحجات والعدوى",
  "Disconnect the electrical current and remove the person using an insulating material": "افصل التيار الكهربائي وأبعد الشخص باستخدام مادة عازلة",
  "Touch the injured person directly to pull him away": "لمس المصاب مباشرة لسحبه بعيداً",
  "Pour water on the injured person": "صب الماء على المصاب",
  "Call the police before doing anything": "الاتصال بالشرطة قبل القيام بأي شيء",
  "3000 to 100,000 ohms": "من 3000 إلى 100,000 أوم",
  "400 to 600 ohms": "من 400 إلى 600 أوم",
  "About 100 ohms": "حوالي 100 أوم",
  "About 1000 ohms": "حوالي 1000 أوم",
  "Heart disorder that may cause death": "اضطراب في القلب قد يسبب الوفاة",
  "A feeling of shock without pain": "إحساس بالصدمة دون ألم",
  "No effect on the body": "لا تأثير على الجسم",
  "Only mild discomfort": "انزعاج خفيف فقط",
  "28 inches": "28 بوصة",
  "18 inches": "18 بوصة",
  "12 inches": "12 بوصة",
  "36 inches": "36 بوصة",
  "45–60 cm": "45–60 سم",
  "10–20 cm": "10–20 سم",
  "100–120 cm": "100–120 سم",
  "150 cm": "150 سم",
  "The science that seeks to protect people from dangers and prevent loss of life and property": "العلم الذي يهدف إلى حماية الناس من الأخطار ومنع فقدان الأرواح والممتلكات",
  "The science of increasing production speed": "علم زيادة سرعة الإنتاج",
  "The rules for using office machines only": "قواعد استخدام الآلات المكتبية فقط",
  "A procedure followed after an accident only": "إجراء يُتبع بعد الحوادث فقط",
  "Protecting human safety and health from work risks by providing a safe work environment": "حماية سلامة وصحة الإنسان من مخاطر العمل عبر توفير بيئة عمل آمنة",
  "Increasing the number of workers in the workplace": "زيادة عدد العمال في مكان العمل",
  "Designing office furniture only": "تصميم الأثاث المكتبي فقط",
  "Reducing the cost of insurance premiums": "خفض تكلفة أقساط التأمين",
  "Plan, Do, Check, Act": "خطط، نفذ، تحقق، صحح",
  "Plan, Act, Do, Check": "خطط، صحح، نفذ، تحقق",
  "Do, Plan, Check, Act": "نفذ، خطط، تحقق، صحح",
  "Check, Do, Act, Plan": "تحقق، نفذ، صحح، خطط",
  "A": "أ",
  "B": "ب",
  "C": "ج",
  "D": "د",
  "First aid": "الإسعافات الأولية",
  "Occupational therapy": "العلاج الوظيفي",
  "Preventive medicine": "الطب الوقائي",
  "Physical rehabilitation": "إعادة التأهيل البدني",
  "Elimination, Substitution, Engineering, Administrative, PPE": "الإزالة، الاستبدال، الضوابط الهندسية، الضوابط الإدارية، معدات الحماية الشخصية",
  "PPE, Administrative, Engineering, Substitution, Elimination": "معدات الحماية، إدارية، هندسية، استبدال، إزالة",
  "Substitution, Elimination, Administrative, Engineering, PPE": "استبدال، إزالة، إدارية، هندسية، معدات حماية",
  "Engineering, Elimination, PPE, Substitution, Administrative": "هندسية، إزالة، معدات حماية، استبدال، إدارية",
  "JSA": "تحليل سلامة العمل (JSA)",
  "HAZID": "تحديد المخاطر (HAZID)",
  "QRA": "تقييم المخاطر الكمي (QRA)",
  "LOPA": "تحليل طبقة الحماية (LOPA)",
  "Only causes and consequences": "الأسباب والعواقب فقط",
  "Hazards, their causes (threats), consequences, and existing safeguards": "المخاطر وأسبابها (التهديدات) وعواقبها والضمانات القائمة",
  "Only consequences and safeguards": "العواقب والضمانات فقط",
  "Only probability and severity": "الاحتمالية والشدة فقط",
  "Reduce the consequence of the hazard": "تقليل عواقب الخطر",
  "Reduce the likelihood of the cause leading to the hazard": "تقليل احتمالية السبب المؤدي إلى الخطر",
  "Transfer the risk to another party": "نقل المخاطر إلى طرف آخر",
  "Increase the hazard severity": "زيادة شدة الخطر",
  "Reduce the likelihood of the cause": "تقليل احتمالية السبب",
  "Eliminate the hazard completely": "إزالة الخطر بالكامل",
  "Delay the work activity": "تأجيل نشاط العمل",
  "Qualitative": "نوعي",
  "Semi-quantitative": "شبه كمي",
  "Quantitative": "كمي",
  "Deterministic": "حتمي",
  "Subjective": "ذاتي",
  "The likelihood of the causes and the impact of the hazard without considering safeguards": "احتمالية الأسباب وتأثير الخطر دون النظر في الضمانات",
  "Only the existing safeguards": "الضمانات القائمة فقط",
  "The residual risk after controls": "الخطر المتبقي بعد الضوابط",
  "The financial cost of the incident": "التكلفة المالية للحادث",
  "At the point of operation, communicated to all employees": "في نقطة التشغيل وإبلاغ جميع الموظفين به",
  "In a locked filing cabinet": "في خزانة ملفات مقفلة",
  "At the company headquarters": "في مقر الشركة",
  "Only with the external auditor": "مع المدقق الخارجي فقط",
  "Low": "منخفض",
  "Medium": "متوسط",
  "Very Low": "منخفض جداً",
  "Negligible": "ضئيل (لا يُذكر)",
  "Finance": "التمويل",
  "HSE field": "مجال الصحة والسلامة والبيئة (HSE)",
  "Procurement": "المشتريات",
  "Public relations": "العلاقات العامة",
  "Installing machine guards and ventilation systems": "تركيب واقيات الآلات وأنظمة التهوية",
  "Job rotation and safety signs": "تناوب الوظائف ولافتات السلامة",
  "Wearing gloves and hard hats": "ارتداء القفازات والخوذ",
  "Writing standard operating procedures": "كتابة إجراءات التشغيل القياسية",
  "Guards on moving parts": "واقيات على الأجزاء المتحركة",
  "Procedures, training, and job rotation": "الإجراءات والتدريب وتناوب الوظائف",
  "Secondary containment": "الاحتواء الثانوي",
  "Pressure safety valves": "صمامات تخفيف الضغط",
  "Empirical": "تجريبي",
  "Roles and responsibilities (Responsible, Accountable, Consulted, Informed)": "الأدوار والمسؤوليات (مسؤول، محاسب، مستشار، مُطّلع)",
  "The cost of risk controls": "تكلفة ضوابط المخاطر",
  "The order of risk treatment": "ترتيب معالجة المخاطر",
  "The hierarchy of controls": "التسلسل الهرمي للضوابط",
  "The chance of an accident": "احتمالية وقوع حادث",
  "A condition with the potential for harm": "حالة تحمل احتمالية التسبب بالضرر",
  "A past incident report": "تقرير حادث سابق",
  "The severity of an injury": "شدة الإصابة",
  "Personal Protective Equipment": "معدات الحماية الشخصية",
  "Elimination": "الإزالة",
  "Administrative controls": "الضوابط الإدارية",
  "Engineering controls": "الضوابط الهندسية",
  "In the office": "في المكتب",
  "At the point of operation": "في نقطة التشغيل",
  "With the safety committee": "مع لجنة السلامة",
  "At the manager's desk": "على مكتب المدير",
  "Substitution": "الاستبدال",
  "Personal Protective Equipment (PPE)": "معدات الحماية الشخصية (PPE)",
  "A wet floor": "أرضية مبللة",
  "Exposure to electricity": "التعرض للكهرباء",
  "Working at height": "العمل على المرتفعات",
  "High or Extreme": "مرتفع أو شديد",
  "Medium or Low": "متوسط أو منخفض",
  "Extreme only": "شديد فقط",
  "High only": "مرتفع فقط",
  "0.25 to 0.75 seconds": "من 0.25 إلى 0.75 ثانية",
  "1 minute exactly": "دقيقة واحدة بالضبط",
  "1 to 2 cm": "من 1 إلى 2 سم",
  "1 to 2 hours": "من ساعة إلى ساعتين",
  "10 compressions to 2 breaths": "10 ضغطات إلى نفختين",
  "10 ohms for all cases without exception": "10 أوم لجميع الحالات دون استثناء",
  "10 to 15 cm": "من 10 إلى 15 سم",
  "10%": "10%",
  "100 to 120 compressions per minute": "من 100 إلى 120 ضغطة في الدقيقة",
  "1000 ohms minimum": "1000 أوم كحد أدنى",
  "12345": "12345",
  "15 compressions to 1 breath": "15 ضغطة إلى نفخة واحدة",
  "150 to 180 compressions per minute": "من 150 إلى 180 ضغطة في الدقيقة",
  "188": "188",
  "2 to 5 minutes": "من دقيقتين إلى 5 دقائق",
  "2%": "2%",
  "20°C (68°F)": "20°م (68°ف)",
  "30 compressions to 2 breaths": "30 ضغطة إلى نفختين",
  "30 to 40 compressions per minute": "من 30 إلى 40 ضغطة في الدقيقة",
  "30°C (86°F)": "30°م (86°ف)",
  "311": "311",
  "35°C (95°F)": "35°م (95°ف)",
  "38°C (100°F)": "38°م (100°ف)",
  "5 compressions to 1 breath": "5 ضغطات إلى نفخة واحدة",
  "5 seconds": "5 ثوانٍ",
  "5 to 10 seconds": "من 5 إلى 10 ثوانٍ",
  "5 to 6 cm (2 inches)": "من 5 إلى 6 سم (بوصتان)",
  "5%": "5%",
  "50%": "50%",
  "60 to 80 compressions per minute": "من 60 إلى 80 ضغطة في الدقيقة",
  "997 or 911": "997 أو 911",
  "A ball valve lockout": "قفل صمام كروي",
  "A change in the weather": "تغيّر في الطقس",
  "A circuit breaker or a disconnect switch": "قاطع دائرة أو مفتاح فصل",
  "A comfortable feature": "ميزة مريحة",
  "A copy of the work permit": "نسخة من تصريح العمل",
  "A cotton cloth only": "قطعة قماش قطنية فقط",
  "A cylinder lockout": "قفل أسطوانة",
  "A direction to the exit": "اتجاه إلى المخرج",
  "A document to enter the office": "مستند للدخول إلى المكتب",
  "A fire extinguisher": "طفاية حريق",
  "A formal commitment by the organization to protect its people and property": "التزام رسمي من المنظمة بحماية موظفيها وممتلكاتها",
  "A formal document that authorizes specific work after safety conditions are met": "مستند رسمي يصرّح بعمل محدد بعد استيفاء شروط السلامة",
  "A gate valve lockout": "قفل صمام بوابة",
  "A general information message": "رسالة معلومات عامة",
  "A high voltage insulated tool used to work on energized equipment from a distance": "أداة معزولة للجهد العالي تُستخدم للعمل على المعدات النشطة عن بُعد",
  "A key for every worker on site": "مفتاح لكل عامل في الموقع",
  "A key stored in the toolbox": "مفتاح محفوظ في صندوق العدة",
  "A lightning strike during a storm": "صاعقة برق أثناء العاصفة",
  "A list of office supplies": "قائمة مستلزمات المكتب",
  "A lock for the locker room": "قفل لغرفة الخزائن",
  "A lock for the office door": "قفل لباب المكتب",
  "A lock for the tool store": "قفل لمخزن العدد",
  "A long-term rehabilitation program": "برنامج تأهيل طويل الأمد",
  "A lunch menu": "قائمة طعام الغداء",
  "A lunch voucher": "قسيمة غداء",
  "A master key kept by the authorized person": "مفتاح رئيسي محفوظ لدى الشخص المصرح له",
  "A metal rod for testing soil": "قضيب معدني لاختبار التربة",
  "A normal notice": "إشعار عادي",
  "A normal spark seen on switches": "شرارة عادية تُرى على المفاتيح",
  "A parking instruction": "تعليمة مواقف",
  "A parking plan": "مخطط مواقف",
  "A plastic bag": "كيس بلاستيكي",
  "A plug prong lockout device": "جهاز قفل لشوكة قابس",
  "A pocket mask or face shield": "قناع جيب أو حاجز وجه",
  "A potentially hazardous situation exists that could cause injury if not avoided": "توجد حالة خطرة محتملة قد تسبب إصابة إذا لم يتم تجنبها",
  "A potentially hazardous situation that could result in death or serious injury if not avoided": "حالة خطرة محتملة قد تؤدي إلى الوفاة أو إصابة خطيرة إذا لم يتم تجنبها",
  "A rest area sign": "لافتة منطقة استراحة",
  "A rod for lifting weights": "قضيب لرفع الأثقال",
  "A safety lock used by authorized personnel during switching or isolation": "قفل سلامة يستخدمه المصرح لهم أثناء التحويل أو العزل",
  "A safety sign": "لافتة سلامة",
  "A safety suggestion": "اقتراح سلامة",
  "A shared lock used by all workers": "قفل مشترك يستخدمه جميع العمال",
  "A sitting upright position": "وضع الجلوس منتصباً",
  "A slight increase in room temperature": "ارتفاع طفيف في درجة حرارة الغرفة",
  "A spare antenna": "هوائي احتياطي",
  "A spare key hidden near the lock": "مفتاح احتياطي مخبأ بالقرب من القفل",
  "A vehicle registration": "استمارة مركبة",
  "A warning sign only": "لافتة تحذير فقط",
  "A-B-C (Airway, Breathing, Circulation)": "المجرى الهوائي، التنفس، الدورة الدموية",
  "Accelerate at the curve": "التسارع عند المنعطف",
  "Accelerate immediately": "التسارع فوراً",
  "Accelerate to race it": "التسارع لمسابقته",
  "Act quickly without documents": "التصرف بسرعة دون مستندات",
  "Advanced Emergency Department": "قسم الطوارئ المتقدم",
  "Affected employee": "الموظف المتأثر",
  "After one hour of waiting": "بعد الانتظار ساعة واحدة",
  "After the work is finished": "بعد انتهاء العمل",
  "All share one common key": "يتشاركون جميعاً في مفتاح واحد مشترك",
  "Always drive faster than others": "القيادة دائماً بسرعة أكبر من الآخرين",
  "An approved switching program and LOTO application": "برنامج تحويل معتمد وتطبيق الإقفال والوسم",
  "An area around the vehicle that cannot be seen in the mirrors": "منطقة حول المركبة لا يمكن رؤيتها في المرايا",
  "An electric current that ionizes the surrounding air and creates an arc with intense heat and light": "تيار كهربائي يؤين الهواء المحيط وينشئ قوساً بحرارة وضوء شديدين",
  "An electrical hazard": "خطر كهربائي",
  "An emergency light": "مصباح طوارئ",
  "An imminently hazardous situation that will cause death or serious injury if not avoided": "حالة خطرة وشيكة ستسبب الوفاة أو إصابة خطيرة إذا لم يتم تجنبها",
  "An improvement": "تحسين",
  "An upside-down position": "وضع مقلوب رأساً على عقب",
  "Anticipate hazards and always be ready to react safely": "توقع المخاطر وكن مستعداً دائماً للتصرف بأمان",
  "Any color with no meaning": "أي لون دون معنى",
  "Any number of keys": "أي عدد من المفاتيح",
  "Any value is acceptable": "أي قيمة مقبولة",
  "Any worker on site": "أي عامل في الموقع",
  "Apply direct pressure with a clean dressing": "الضغط المباشر بضمادة نظيفة",
  "Apply earths first, then isolate": "تطبيق التأريض أولاً ثم العزل",
  "Apply lock, notify, verify, shutdown, release energy": "وضع القفل، الإبلاغ، التحقق، الإيقاف، تحرير الطاقة",
  "Apply the lock": "وضع القفل",
  "Applying your own lock": "وضع قفلك الخاص",
  "Approach (approach boundary) distance": "مسافة الاقتراب (حد الاقتراب)",
  "Arc-rated clothing, hearing protection, eye protection and head protection": "ملابس مقاومة للقوس الكهربائي وحماية للسمع والعينين والرأس",
  "Are never locked": "لا تُقفل أبداً",
  "Arrange the parking": "تنظيم المواقف",
  "As a last resort to control severe bleeding that cannot be stopped otherwise, and only by trained persons": "كحل أخير للسيطرة على النزيف الشديد الذي لا يمكن إيقافه بغير ذلك، وبواسطة أشخاص مدرَّبين فقط",
  "As deep as possible": "بأعمق ما يمكن",
  "As specified in the ground resistance table for the installation type": "كما هو محدد في جدول مقاومة التأريض حسب نوع التركيب",
  "Ask a coworker": "سؤال زميل",
  "Ask for a gift": "طلب هدية",
  "At a desk": "على مكتب",
  "At all times without exception": "في جميع الأوقات دون استثناء",
  "At least 20 seconds": "على الأقل 20 ثانية",
  "At the end of each shift": "في نهاية كل وردية",
  "Automated External Defibrillator": "جهاز الصدمات الخارجية الآلي (AED)",
  "Automatic Energy Device": "جهاز الطاقة الآلي",
  "Auxiliary Electric Defibrillator": "مزيل الرجفان الكهربائي المساعد",
  "Available for use": "متاح للاستخدام",
  "B-A-C (Breathing, Airway, Circulation)": "التنفس، المجرى الهوائي، الدورة الدموية",
  "Back up onto the highway": "الرجوع إلى الخلف على الطريق السريع",
  "Bare hands": "اليدين العاريتين",
  "Be authorized and follow the approved switching program": "أن يكون مصرحاً له وأن يتبع برنامج التحويل المعتمد",
  "Be completed quickly": "أن يُنجز بسرعة",
  "Be ignored": "أن يُتجاهل",
  "Be stopped immediately and the violation reported": "أن يُوقف فوراً ويُبلغ عن المخالفة",
  "Because red paint is cheaper": "لأن الطلاء الأحمر أرخص",
  "Bending the head backwards": "ثني الرأس إلى الخلف",
  "Black": "أسود",
  "Black only": "الأسود فقط",
  "Block all emergency exits": "سد جميع مخارج الطوارئ",
  "Block the emergency exits": "سد مخارج الطوارئ",
  "Blue and black": "الأزرق والأسود",
  "Both fists": "كلتا اليدين المقبوضتين",
  "Brake hard frequently": "الفرملة القوية بشكل متكرر",
  "Brake suddenly": "الفرملة المفاجئة",
  "Brake suddenly in the fast lane": "الفرملة المفاجئة في المسار السريع",
  "Braking distance only": "مسافة الكبح فقط",
  "Braking time": "زمن الكبح",
  "Bright office lighting": "إضاءة مكتبية ساطعة",
  "Brown": "بني",
  "By any worker on shift": "بواسطة أي عامل في الوردية",
  "By lifting both legs": "برفع الساقين معاً",
  "By pressing on the stomach": "بالضغط على المعدة",
  "By shaking the head strongly": "بهز الرأس بقوة",
  "C-A-B (Circulation, Airway, Breathing)": "الدورة الدموية، المجرى الهوائي، التنفس",
  "C-B-A (Circulation, Breathing, Airway)": "الدورة الدموية، التنفس، المجرى الهوائي",
  "Call the victim's family first": "الاتصال بعائلة المصاب أولاً",
  "Can be opened by any person": "يمكن فتحه من قبل أي شخص",
  "Car parking distance": "مسافة مواقف السيارات",
  "Cardiac pulse recovery": "استعادة النبض القلبي",
  "Cardiopulmonary resuscitation": "الإنعاش القلبي الرئوي",
  "Center of the lane with a safe distance from other vehicles": "وسط المسار مع مسافة آمنة من المركبات الأخرى",
  "Change in the smell of the air": "تغير في رائحة الهواء",
  "Change lane without signaling": "تغيير المسار دون إشارة",
  "Change the permit himself": "تعديل التصريح بنفسه",
  "Check mirrors and blind spots, and signal": "فحص المرايا والنقاط العمياء والإشارة",
  "Check the scene for safety": "التحقق من أمان مكان الحادث",
  "Check the voltage tester": "فحص جهاز اختبار الجهد",
  "Chest pressure release": "إطلاق الضغط على الصدر",
  "Cleaned only": "يُنظف فقط",
  "Cleaning materials": "مواد تنظيف",
  "Clinical patient review": "مراجعة حالة المريض السريرية",
  "Close his eyes and count": "إغلاق عينيه والعد",
  "Close his eyes and cross": "إغلاق عينيه والعبور",
  "Close his eyes at the curve": "إغلاق عينيه عند المنعطف",
  "Close the eyes": "إغلاق العينين",
  "Coated with wet paint": "مغطى بطلاء رطب",
  "Comply with all permit conditions and the site safety rules": "الامتثال لجميع شروط التصريح وقواعد السلامة في الموقع",
  "Continue to the next exit": "الاستمرار إلى المخرج التالي",
  "Continue until the end of the shift": "الاستمرار حتى نهاية الوردية",
  "Continue working quietly": "مواصلة العمل بهدوء",
  "Control bleeding, preserve the severed part in a clean damp cloth, and call emergency": "السيطرة على النزيف وحفظ الجزء المقطوع في قطعة قماش نظيفة رطبة والاتصال بالطوارئ",
  "Cotton gloves": "قفازات قطنية",
  "Count the tools quickly": "عدّ العدد بسرعة",
  "Cover it with a tarp": "تغطيته بمشمع",
  "Cross immediately without slowing": "العبور فوراً دون تخفيف السرعة",
  "Cross the center line": "تجاوز الخط الأوسط",
  "Daily before use and immediately after any incident": "يومياً قبل الاستخدام وبشكل فوري بعد أي حادث",
  "Damage and proper insulation": "التلف وسلامة العزل",
  "Decorate the equipment": "تزيين المعدات",
  "Decorate the site": "تزيين الموقع",
  "Decorating the installation": "تزيين التركيبات",
  "Destroy the permit": "إتلاف التصريح",
  "Discard the inspection record": "التخلص من سجل الفحص",
  "Discarded without a record": "يُتخلص منه دون سجل",
  "Discharge, depressurize, and drain all stored energy sources": "تفريغ مصادر الطاقة المخزنة وإزالة الضغط عنها",
  "Distracts the driver and increases the risk of accidents": "يشتت انتباه السائق ويزيد من خطر الحوادث",
  "Do not start the work and return the permit to the issuer": "عدم بدء العمل وإعادة التصريح إلى الجهة المُصدرة",
  "Drinking too much water": "شرب كميات كبيرة من الماء",
  "Drive in the opposite lane": "القيادة في المسار المعاكس",
  "Drive on the emergency shoulder in reverse": "القيادة على كتف الطريق في الاتجاه المعاكس",
  "Drive without headlights": "القيادة دون أضواء أمامية",
  "Driver License": "رخصة قيادة",
  "Driving at the maximum speed at all times": "القيادة بالسرعة القصوى في جميع الأوقات",
  "Driving in a way that anticipates hazards and prepares to react to other road users": "القيادة بطريقة تتوقع المخاطر وتستعد للتعامل مع مستخدمي الطريق الآخرين",
  "Driving time": "زمن القيادة",
  "Driving with one hand on the wheel": "القيادة بيد واحدة على المقود",
  "Dust in the office": "الغبار في المكتب",
  "Each worker adds his own personal lock to a lockout hasp": "يضيف كل عامل قفله الشخصي إلى مشبك الإقفال",
  "Electric arcs, flashes, or flying objects from an electrical explosion": "أقواس أو ومضات كهربائية أو أجسام متطايرة ناتجة عن انفجار كهربائي",
  "Electric arcs, flashes, or flying objects resulting from an electrical explosion": "أقواس أو ومضات كهربائية أو أجسام متطايرة ناتجة عن انفجار كهربائي",
  "Electrical": "كهربائي",
  "Ensure only qualified persons receive authorization": "ضمان أن المصرح لهم هم الأشخاص المؤهلون فقط",
  "Enter quickly without checks": "الدخول بسرعة دون فحوصات",
  "Equipment supplier": "مورد المعدات",
  "Every five years": "كل خمس سنوات",
  "Excessive appetite": "الشهية المفرطة",
  "External auditor": "مراجع خارجي",
  "Extra light": "إضاءة إضافية",
  "Face drooping or weakness of one arm": "تدلّي الوجه أو ضعف أحد الذراعين",
  "Failure of the body's temperature regulator, causing dangerously high body temperature": "فشل منظم حرارة الجسم مما يسبب ارتفاعاً خطيراً في درجة الحرارة",
  "Fan the flames": "تهوية اللهب",
  "Fire, explosion, burns, and injury from metal fragments": "حريق وانفجار وحروق وإصابات من شظايا معدنية",
  "First, second, and third degree burns": "حروق من الدرجة الأولى والثانية والثالثة",
  "Follow only his own instructions": "اتباع تعليماته الخاصة فقط",
  "Follow the car in front very closely": "الاقتراب كثيراً من السيارة الأمامية",
  "Follow the vehicle ahead closely": "ملازمة المركبة التي أمامك",
  "Food preparation": "تحضير الطعام",
  "For a headache": "لعلاج الصداع",
  "For a nosebleed": "لعلاج نزيف الأنف",
  "For any small cut": "لأي جرح صغير",
  "Fresh air": "الهواء النقي",
  "Give 5 back blows and 5 chest thrusts": "إعطاء 5 ضربات على الظهر و5 ضغطات على الصدر",
  "Give him water immediately": "إعطاؤه الماء فوراً",
  "Give water to the victim": "إعطاء الماء للمصاب",
  "Green and yellow": "الأخضر والأصفر",
  "Green only": "الأخضر فقط",
  "Grey": "رمادي",
  "Half a car length": "نصف طول سيارة",
  "Half on the shoulder": "النصف على الكتف",
  "Has no effect on driving": "لا تأثير له على القيادة",
  "Has the same effect as driving normally": "له نفس تأثير القيادة العادية",
  "Have different colors and an individual key differing from normal system locks": "تكون بألوان مختلفة ومفتاح فردي يختلف عن أقفال النظام العادية",
  "Hazard Level Warning": "تحذير مستوى الخطورة",
  "He drives on the hard shoulder": "يقود على الكتف الصلب",
  "He sounds the horn continuously": "يطلق البوق باستمرار",
  "Head-tilt and chin-lift maneuver": "إمالة الرأس ورفع الذقن",
  "Heat or arcing": "الحرارة أو التكهرب",
  "Heavy Lifting Work": "أعمال الرفع الثقيلة",
  "Hide equipment": "إخفاء المعدات",
  "Hide the equipment": "إخفاء المعدات",
  "High Load Work": "أعمال الأحمال العالية",
  "His own lock with his own key": "قفله الخاص بمفتاحه الخاص",
  "Hold the infant upside down": "إمساك الرضيع مقلوباً",
  "Honk and change immediately": "إطلاق البوق وتغيير المسار فوراً",
  "Honk continuously": "إطلاق البوق باستمرار",
  "Hot Line Work": "العمل على الخطوط النشطة",
  "Human error": "الخطأ البشري",
  "Ignore it because it is small": "تجاهله لأنه صغير",
  "Ignore the change": "تجاهل التغيير",
  "Ignore the signal": "تجاهل الإشارة",
  "Immediate medical assistance given to an injured or suddenly ill person before professional help arrives": "مساعدة طبية فورية تُقدَّم لشخص مصاب أو مريض بشكل مفاجئ قبل وصول المساعدة المهنية",
  "Immediately with bolt cutters": "فوراً باستخدام قاطعة الأقفال",
  "Improve ventilation": "تحسين التهوية",
  "In the cafeteria": "في الكافتيريا",
  "In the parking lot": "في موقف السيارات",
  "In the suitable location before work and removed only after work is completed": "في المكان المناسب قبل العمل ولا تُزال إلا بعد اكتماله",
  "Increase speed": "زيادة السرعة",
  "Increase speed rapidly": "زيادة السرعة بسرعة",
  "Increase the light in the area": "زيادة الإضاءة في المنطقة",
  "Increasing the voltage": "زيادة الجهد",
  "Inform the plant operator": "إبلاغ مشغل المنشأة",
  "Inspect the equipment for damage": "فحص المعدات بحثاً عن التلف",
  "Inspected immediately before further use": "يُفحص مباشرة قبل الاستخدام مرة أخرى",
  "Instructions for swimming": "تعليمات السباحة",
  "Insulated with rubber": "معزول بالمطاط",
  "Insulating gloves, helmet, and appropriate clothing": "قفازات عازلة وخوذة وملابس مناسبة",
  "Is a new employee": "هو موظف جديد",
  "Is allowed at any time": "مسموح في أي وقت",
  "Is qualified and authorized to perform specific safety roles": "مؤهل ومصرح له بأداء أدوار سلامة محددة",
  "Is safe if the driver holds it near the wheel": "آمن إذا أمسكه السائق بالقرب من المقود",
  "Is safer than driving alert": "أكثر أماناً من القيادة في حالة يقظة",
  "Isolate the power and rescue the person safely without touching him directly": "عزل التيار وإنقاذ الشخص بأمان دون لمسه مباشرة",
  "Isolate, notify, apply tag, verify, shutdown": "العزل، الإبلاغ، وضع البطاقة، التحقق، الإيقاف",
  "Isolate, verify zero energy, apply earths, and obtain authorization": "العزل والتحقق من انعدام الطاقة وتطبيق التأريض والحصول على التصريح",
  "Isolated, locked out, and verified de-energized": "معزول ومقفل وتم التحقق من انعدام طاقته",
  "Its color": "لونه",
  "Its length only": "طوله فقط",
  "Jump into a confined area": "القفز إلى مكان مغلق",
  "Keep a safe distance, stay patient, and avoid aggression": "الحفاظ على مسافة آمنة والتحلي بالصبر وتجنب العدوانية",
  "Keep his lane, maintain speed, and let the vehicle overtake safely": "البقاء في مساره والحفاظ على السرعة وترك المركبة تتجاوز بأمان",
  "Keep people away from hazards and protect work areas": "إبعاد الأشخاص عن المخاطر وحماية مناطق العمل",
  "Keep the permit as a souvenir": "الاحتفاظ بالتصريح كتذكار",
  "Keeps the worker warm": "يحافظ على دفء العامل",
  "Kept wet during work": "يُحفظ رطباً أثناء العمل",
  "Key safety rules that must never be violated because they prevent fatal incidents": "قواعد سلامة أساسية لا يجوز مخالفتها أبداً لأنها تمنع الحوادث المميتة",
  "Label spare parts": "وضع ملصقات على قطع الغيار",
  "Labeled with a price": "مُعلّم بعلامة سعر",
  "Leather work gloves": "قفازات عمل جلدية",
  "Leave the permit at the site": "ترك التصريح في الموقع",
  "Leave the wound open and wet": "ترك الجرح مفتوحاً ورطباً",
  "Level of Thermal Output": "مستوى المخرجات الحرارية",
  "Lines are usually not insulated and can cause electrocution": "الخطوط عادة غير معزولة وقد تسبب الصعق الكهربائي",
  "Listen for a humming sound": "الاستماع لأي صوت طنين",
  "Load and Test Operations": "عمليات التحميل والاختبار",
  "Lockout/Tagout": "الإقفال والوسم",
  "Locks and keys that secure the isolation of equipment": "أقفال ومفاتيح تضمن عزل المعدات",
  "Locks are not needed when working together": "لا حاجة للأقفال عند العمل معاً",
  "Looks professional": "يبدو احترافياً",
  "Loss of Tool Output": "فقدان مخرجات الأداة",
  "Lunch Break Card": "بطاقة استراحة الغداء",
  "Lunch break distance": "مسافة استراحة الغداء",
  "Lunch supplies": "مستلزمات الغداء",
  "Lying flat on the back": "الاستلقاء على الظهر",
  "Made of aluminum foil": "مصنوع من ورق الألمنيوم",
  "Making the wires heavier": "جعل الأسلاك أثقل",
  "Mark parking spaces": "تحديد أماكن المواقف",
  "May be energized and cause shock if touched": "قد تكون نشطة وتسبب صعقاً إذا لمستها",
  "Mechanical": "ميكانيكي",
  "Merge without looking": "الاندماج دون النظر",
  "Metallic": "معدني",
  "Mild and severe only": "خفيفة وشديدة فقط",
  "Minor noise": "ضوضاء طفيفة",
  "Modify the permit quietly": "تعديل التصريح بهدوء",
  "Monthly": "شهرياً",
  "Move the victim immediately": "نقل المصاب فوراً",
  "Never": "أبداً",
  "Never stop at intersections": "عدم التوقف أبداً عند التقاطعات",
  "New trainees without supervision": "متدربون جدد دون إشراف",
  "No PPE is required": "لا تُشترط معدات الحماية الشخصية",
  "No damage at all": "لا يوجد أي تلف",
  "No distance is needed": "لا حاجة لأي مسافة",
  "No, master keys are forbidden for workers": "لا، المفاتيح الرئيسية محظورة على العمال",
  "Nobody is touching the victim": "لا أحد يلمس المصاب",
  "Non-conductive": "غير موصل",
  "Not important": "غير مهم",
  "Not insulated": "غير معزول",
  "Notify all affected employees": "إبلاغ جميع الموظفين المتأثرين",
  "Notify, shutdown, isolate, apply lock/tag, release stored energy, verify": "الإبلاغ، الإيقاف، العزل، وضع القفل/البطاقة، تحرير الطاقة المخزنة، التحقق",
  "Obtain the required authorization and follow the entry procedure": "الحصول على التصريح المطلوب واتباع إجراءات الدخول",
  "Office cleaning": "تنظيف المكاتب",
  "Office door distance": "مسافة باب المكتب",
  "Oiled": "مزيت",
  "On or near energized electrical conductors and equipment": "على أو بالقرب من الموصلات والمعدات الكهربائية النشطة",
  "On the abdomen": "على البطن",
  "On the lane markings": "على علامات المسار",
  "On the left side of the chest": "على الجانب الأيسر من الصدر",
  "On the lower half of the breastbone (sternum) in the center of the chest": "على النصف السفلي من عظمة القص في منتصف الصدر",
  "On the neck": "على الرقبة",
  "Once a year": "مرة واحدة في السنة",
  "Once a year only": "مرة واحدة في السنة فقط",
  "One key": "مفتاح واحد",
  "One knee": "ركبة واحدة",
  "One meter": "متر واحد",
  "Only a cotton cap": "غطاء قطن فقط",
  "Only a safety vest": "سترة سلامة فقط",
  "Only a small light": "ضوء صغير فقط",
  "Only a verbal order": "أمر شفهي فقط",
  "Only affects long trips": "يؤثر على الرحلات الطويلة فقط",
  "Only after an accident": "فقط بعد وقوع حادث",
  "Only after following the approved procedure and verifying no hazardous energy exists": "فقط بعد اتباع الإجراء المعتمد والتحقق من عدم وجود طاقة خطرة",
  "Only at the end of the day": "فقط في نهاية اليوم",
  "Only by managers": "فقط بواسطة المديرين",
  "Only cotton gloves": "قفازات قطنية فقط",
  "Only during audits": "فقط أثناء عمليات التدقيق",
  "Only during night shifts": "فقط أثناء الورديات الليلية",
  "Only during rain": "فقط أثناء المطر",
  "Only gloves for cold weather": "قفازات للطقس البارد فقط",
  "Only on rainy days": "فقط في الأيام الممطرة",
  "Only safety shoes": "أحذية سلامة فقط",
  "Only sign the permit": "التوقيع على التصريح فقط",
  "Only the supervisor applies one lock": "فقط المشرف يضع قفلاً واحداً",
  "Only when an energy-isolating device cannot be locked": "فقط عندما لا يمكن قفل جهاز عزل الطاقة",
  "Open the fence by himself": "فتح السياج بنفسه",
  "Out of service and must not be operated": "خارج الخدمة ولا يجوز تشغيله",
  "Owns a car": "يمتلك سيارة",
  "Pain in the big toe": "ألم في إصبع القدم الكبير",
  "Paint the equipment": "طلاء المعدات",
  "Painted": "مطلي",
  "Parking is available": "المواقف متاحة",
  "Pat him on the back gently": "التربيت على ظهره بلطف",
  "Perform abdominal thrusts": "أداء الضغطات البطنية",
  "Perform abdominal thrusts (Heimlich maneuver)": "أداء الضغطات البطنية (مناورة هيمليك)",
  "Personal Emergency Alarm": "إنذار الطوارئ الشخصي",
  "Photographed": "مصوَّر",
  "Pink": "وردي",
  "Pink and grey": "وردي ورمادي",
  "Plan and authorize the isolation and de-energizing of equipment": "تخطيط عزل وفصل الطاقة عن المعدات والتصريح بذلك",
  "Plan the office cleaning": "التخطيط لتنظيف المكتب",
  "Plastic gloves": "قفازات بلاستيكية",
  "Portable Earth Application": "تطبيق التأريض المحمول",
  "Pour water on the person": "صب الماء على الشخص",
  "Power Equipment Area": "منطقة المعدات الكهربائية",
  "Prepare to stop safely": "الاستعداد للتوقف بأمان",
  "Prevent accidental energization and protect workers from hazardous energy": "منع التفعيل العرضي للطاقة وحماية العمال من الطاقة الخطرة",
  "Prevents or reduces burns from the arc flash": "يمنع أو يقلل الحروق الناتجة عن وميض القوس الكهربائي",
  "Primary Energy Assessment": "التقييم الأولي للطاقة",
  "Print cards faster": "طباعة البطاقات بسرعة أكبر",
  "Proceed with a verbal agreement": "المتابعة بموافقة شفهية",
  "Protect people from hazards and define restricted areas": "حماية الأشخاص من المخاطر وتحديد المناطق المقيّدة",
  "Providing a low-resistance path that trips protective devices and prevents shock": "توفير مسار منخفض المقاومة يؤدي إلى تشغيل أجهزة الحماية ومنع الصعق",
  "Racing on public roads": "التسابق على الطرق العامة",
  "Rated for the voltage of the work and inspected before each use": "مصمم لجهد العمل ويُفحص قبل كل استخدام",
  "Reaction distance + braking distance": "مسافة رد الفعل + مسافة الكبح",
  "Reaction distance only": "مسافة رد الفعل فقط",
  "Reaction time": "زمن رد الفعل",
  "Reading documents": "قراءة المستندات",
  "Ready for operation": "جاهز للتشغيل",
  "Reattach the part immediately": "إعادة تركيب الجزء فوراً",
  "Record attendance": "تسجيل الحضور",
  "Red and blue burns": "حروق حمراء وزرقاء",
  "Red and white": "أحمر وأبيض",
  "Red, blue, or white in color": "أحمر أو أزرق أو أبيض اللون",
  "Reduce paperwork": "تقليل الأعمال الورقية",
  "Reduce speed and increase the following distance": "تخفيف السرعة وزيادة مسافة التتبع",
  "Reduce speed before the curve and stay in the lane": "تخفيف السرعة قبل المنعطف والبقاء في المسار",
  "Reduce the number of workers": "تقليل عدد العمال",
  "Reduce the room temperature": "خفض درجة حرارة الغرفة",
  "Reduces reaction time and is dangerous": "يقلل زمن رد الفعل وهو خطير",
  "Release stored energy": "تحرير الطاقة المخزنة",
  "Remove the lock": "إزالة القفل",
  "Removing locks, shortcuts, and operating locked equipment": "إزالة الأقفال واختصار الإجراءات وتشغيل معدات مقفلة",
  "Removing the locks": "إزالة الأقفال",
  "Replaces the arc flash hazard": "يحل محل خطر وميض القوس الكهربائي",
  "Rest time": "زمن الراحة",
  "Return the permit to the issuer after the site is restored and safe": "إعادة التصريح إلى الجهة المُصدرة بعد إعادة الموقع إلى حالته الآمنة",
  "Reverse into the exit": "الرجوع إلى الخلف في المخرج",
  "Road width": "عرض الطريق",
  "Rubber insulating gloves": "قفازات مطاطية عازلة",
  "Rules for saving money": "قواعد الادخار",
  "Rules for using the elevator": "قواعد استخدام المصعد",
  "Run as fast as possible": "الجري بأقصى سرعة",
  "Runny nose": "سيلان الأنف",
  "Safe to touch": "آمن للمس",
  "Safety To Work": "تصريح السلامة للعمل",
  "Safety Training Workshop": "ورشة تدريب السلامة",
  "Sanction For Test (S.F.T)": "تصريح الاختبار (S.F.T)",
  "Sanction To Work": "تصريح العمل",
  "Sanction To Work (S.T.W)": "تصريح العمل (S.T.W)",
  "Schedule the lunch break": "جدولة استراحة الغداء",
  "Severe burns, hearing damage, and eye injury from intense heat, light, and sound": "حروق شديدة وتلف في السمع وإصابة في العينين من الحرارة والضوء والصوت الشديدين",
  "Shutdown, verify, notify, apply lock, release energy": "الإيقاف، التحقق، الإبلاغ، وضع القفل، تحرير الطاقة",
  "Signal early and slow down in the exit lane": "الإشارة مبكراً وتخفيف السرعة في مسار المخرج",
  "Site nurse": "ممرض الموقع",
  "Sitting up, leaning forward, and pinching the nostrils": "الجلوس والانحناء للأمام والضغط على الأنف",
  "Skip the safety briefing": "تخطي إحاطة السلامة",
  "Skip the safety signs": "تجاهل لافتات السلامة",
  "Skip the site visit": "تخطي زيارة الموقع",
  "Skipping breakfast": "تخطي وجبة الإفطار",
  "Slap the infant on the head": "صفع الرضيع على الرأس",
  "Slow down, look in all directions, and be ready to stop": "تخفيف السرعة والنظر في جميع الاتجاهات والاستعداد للتوقف",
  "Sound the horn and speed up": "إطلاق البوق وزيادة السرعة",
  "Spare tools": "عدد احتياطية",
  "Specially trained and authorized personnel with the required documents and tools": "أفراد مدربون ومصرح لهم بشكل خاص ومعهم المستندات والعدد المطلوبة",
  "Speed up the work": "تسريع العمل",
  "Standard Training Work": "أعمال التدريب القياسية",
  "Standing against a wall": "الوقوف مقابل الحائط",
  "Standing upside down": "الوقوف مقلوباً",
  "Start the equipment": "تشغيل المعدات",
  "Start the work anyway": "بدء العمل على أي حال",
  "Start work directly": "بدء العمل مباشرة",
  "Stop and reverse on the highway": "التوقف والرجوع إلى الخلف على الطريق السريع",
  "Stop at the entrance": "التوقف عند المدخل",
  "Stop at the exit point": "التوقف عند نقطة الخروج",
  "Stop work and inform the issuer": "إيقاف العمل وإبلاغ الجهة المُصدرة",
  "Stop, drop to the ground, and roll": "قف، انزل إلى الأرض، وتدحرج",
  "Store the equipment away": "تخزين المعدات بعيداً",
  "Stored without inspection": "يُخزن دون فحص",
  "Sunlight through the window": "ضوء الشمس عبر النافذة",
  "Switch Test Warning": "تحذير اختبار المفاتيح",
  "Switch Test Window": "نافذة اختبار المفاتيح",
  "Switching operations and work on energized equipment": "عمليات التحويل والعمل على المعدات النشطة",
  "System Technical Work": "أعمال فنية على الأنظمة",
  "Test the equipment using an approved voltage tester": "اختبار المعدات باستخدام جهاز فحص جهد معتمد",
  "Tested to verify zero energy and grounded if required": "يُختبر للتأكد من انعدام الطاقة ويُؤرَّض إذا لزم",
  "The LOTO lock and tag cutting and removal form": "نموذج قص وإزالة الأقفال والبطاقات في نظام الإقفال والوسم",
  "The arcing hazard": "خطر التكهرب",
  "The area above the roof": "المنطقة فوق السقف",
  "The area directly in front of the windscreen": "المنطقة الواقعة مباشرة أمام الزجاج الأمامي",
  "The authorized person who checks the safety conditions and issues the permit": "الشخص المصرح له الذي يتحقق من شروط السلامة ويصدر التصريح",
  "The authorized person who receives the permit and is responsible for the work team": "الشخص المصرح له الذي يستلم التصريح ويكون مسؤولاً عن فريق العمل",
  "The brand name": "اسم العلامة التجارية",
  "The cafeteria is open": "الكافتيريا مفتوحة",
  "The color of the equipment": "لون المعدات",
  "The equipment color code": "رمز الألوان للمعدات",
  "The faster vehicle": "المركبة الأسرع",
  "The final medical treatment in hospital": "العلاج الطبي النهائي في المستشفى",
  "The hazard identification form": "نموذج تحديد المخاطر",
  "The hazard level and required PPE for the equipment": "مستوى الخطورة ومعدات الحماية المطلوبة للمعدات",
  "The height of the worker": "طول العامل",
  "The larger vehicle": "المركبة الأكبر",
  "The light of a lamp": "ضوء المصباح",
  "The lines are very heavy": "الخطوط ثقيلة جداً",
  "The lines block the view": "الخطوط تحجب الرؤية",
  "The lines make noise": "الخطوط تصدر ضوضاء",
  "The lunch menu": "قائمة الغداء",
  "The manufacturing year": "سنة التصنيع",
  "The monthly PPE inspection form": "نموذج الفحص الشهري لمعدات الحماية",
  "The noise level": "مستوى الضوضاء",
  "The office attendance sheet": "ورقة الحضور في المكتب",
  "The office is closed": "المكتب مغلق",
  "The person who prints the permit": "الشخص الذي يطبع التصريح",
  "The person who stores the permits": "الشخص الذي يحفظ التصاريح",
  "The price of the equipment": "سعر المعدات",
  "The recovery position": "وضعية التعافي",
  "The road ahead is clear and overtaking is safe and legal": "الطريق أمامك خالٍ وأن التجاوز آمن وقانوني",
  "The room is completely dark": "الغرفة مظلمة تماماً",
  "The room temperature": "درجة حرارة الغرفة",
  "The security guard": "حارس الأمن",
  "The shadow under the vehicle": "الظل أسفل المركبة",
  "The site is clean": "الموقع نظيف",
  "The time of the day": "وقت اليوم",
  "The training attendance form": "نموذج حضور التدريب",
  "The two-second rule": "قاعدة الثانيتين",
  "The use of advanced surgical equipment": "استخدام المعدات الجراحية المتقدمة",
  "The vehicle behind speeds up": "المركبة الخلفية تزيد سرعتها",
  "The vehicle length": "طول المركبة",
  "The vehicle registration": "استمارة المركبة",
  "The victim is covered with a blanket": "المصاب مغطى ببطانية",
  "The victim is sitting up": "المصاب جالس",
  "The visitor": "الزائر",
  "The visitor who watches the work": "الزائر الذي يشاهد العمل",
  "The voltage difference between two points one step apart on energized ground": "فرق الجهد بين نقطتين متباعدتين بخطوة واحدة على الأرض النشطة",
  "The voltage level and the approach boundary tables": "مستوى الجهد وجداول حدود الاقتراب",
  "The voltage of a battery": "جهد البطارية",
  "The voltage of a street light": "جهد إنارة الشوارع",
  "The voltage of household lighting": "جهد إضاءة المنازل",
  "The voltage of the car battery": "جهد بطارية السيارة",
  "The voltage of the human heart": "جهد قلب الإنسان",
  "The voltage that appears when a person touches energized equipment while standing on lower-voltage ground": "الجهد الذي يظهر عندما يلمس شخص معدات نشطة وهو واقف على أرض ذات جهد أقل",
  "The voltage used to charge phones": "الجهد المستخدم لشحن الهواتف",
  "The weather is clear": "الطقس صافٍ",
  "The whole palm": "راحة اليد بأكملها",
  "The wind direction": "اتجاه الرياح",
  "The work permit and its approval workflow": "تصريح العمل وسير الموافقة عليه",
  "There is a rest area": "توجد منطقة استراحة",
  "There is an imminently hazardous situation": "توجد حالة خطرة وشيكة",
  "Thermal": "حراري",
  "They share one lock between them": "يتشاركون قفلاً واحداً بينهم",
  "Three keys": "ثلاثة مفاتيح",
  "Throw the severed part away": "رمي الجزء المقطوع",
  "Tie a tight rope above the wound": "ربط حبل محكم فوق الجرح",
  "To advertise a product": "للإعلان عن منتج",
  "To attract visitors": "لجذب الزوار",
  "To bring tools to the site": "لإحضار العدد إلى الموقع",
  "To calculate overtime": "لحساب ساعات العمل الإضافية",
  "To carry out the work safely and comply with all permit conditions": "لتنفيذ العمل بأمان والامتثال لجميع شروط التصريح",
  "To design new equipment": "لتصميم معدات جديدة",
  "To do the work on the equipment": "لأداء العمل على المعدات",
  "To ensure equipment is de-energized and cannot be re-energized during work": "لضمان فصل الطاقة عن المعدات وعدم إعادة تفعيلها أثناء العمل",
  "To ensure the work site is safe and the permit conditions are correct before signing": "للتأكد من أن موقع العمل آمن وأن شروط التصريح صحيحة قبل التوقيع",
  "To identify equipment that must not be operated": "لتحديد المعدات التي لا يجوز تشغيلها",
  "To identify that the equipment is energized and locked for electrical work": "لتحديد أن المعدات نشطة ومقفلة لأجل العمل الكهربائي",
  "To identify the content and flow direction for safety": "لتحديد المحتوى واتجاه التدفق لأغراض السلامة",
  "To increase the pressure": "لزيادة الضغط",
  "To isolate the worker from his supervisor": "لعزل العامل عن مشرفه",
  "To keep tools in the workshop": "لإبقاء الأدوات في الورشة",
  "To label the storage room": "لوضع ملصقات على غرفة التخزين",
  "To light the work area": "لإضاءة منطقة العمل",
  "To list spare parts": "لإعداد قائمة قطع الغيار",
  "To make the pipes look nice": "لجعل الأنابيب تبدو جميلة",
  "To mark the work site": "لتحديد موقع العمل",
  "To match the company logo": "ليطابق شعار الشركة",
  "To prepare the meals": "لتحضير الوجبات",
  "To prevent accidental startup or release of hazardous energy during maintenance": "لمنع التشغيل العرضي أو تحرير الطاقة الخطرة أثناء الصيانة",
  "To provide a safe path for any residual or induced current": "لتوفير مسار آمن لأي تيار متبقٍ أو مستحث",
  "To record attendance": "لتسجيل الحضور",
  "To record employee attendance": "لتسجيل حضور الموظفين",
  "To record that LOTO procedures are inspected and verified periodically": "لتسجيل أن إجراءات الإقفال والوسم تُفحص وتُتحقق منها دورياً",
  "To reduce the noise": "لتقليل الضوضاء",
  "To reduce the number of workers": "لتقليل عدد العمال",
  "To replace the equipment operator": "لاستبدال مشغل المعدات",
  "To sign permits for other teams": "لتوقيع تصاريح الفرق الأخرى",
  "To speed up equipment repairs": "لتسريع إصلاح المعدات",
  "To speed up the work": "لتسريع العمل",
  "To supervise unrelated departments": "للإشراف على أقسام غير ذات صلة",
  "To warm the pipes": "لتدفئة الأنابيب",
  "Touch the person to pull him away": "لمس الشخص لسحبه بعيداً",
  "Touch unverified conductors or use damaged tools": "لمس الموصلات غير المفحوصة أو استخدام عدد تالفة",
  "Track visitor attendance": "تتبع حضور الزوار",
  "Traffic already circulating inside the roundabout": "المركبات التي تسير بالفعل داخل الدوار",
  "Traffic entering the roundabout": "المركبات الداخلة إلى الدوار",
  "Trust that the lock is applied": "الوثوق بأن القفل مُطبق",
  "Turn around immediately": "الاستدارة فوراً",
  "Two fingers on the center of the chest just below the nipple line": "إصبعان في منتصف الصدر أسفل خط الحلمة مباشرة",
  "Two keys only": "مفتاحان فقط",
  "Under annual inspection only": "تحت الفحص السنوي فقط",
  "Underground": "تحت الأرض",
  "Until the water runs out": "حتى نفاد الماء",
  "Use headlights and reduce speed": "استخدام الأضواء الأمامية وتخفيف السرعة",
  "Use only parking lights": "استخدام أضواء المواقف فقط",
  "Use the acceleration lane and match the speed of traffic": "استخدام مسار التسارع ومواكبة سرعة المرور",
  "Use the emergency lane": "استخدام المسار الطارئ",
  "Use the equipment without authorization": "استخدام المعدات دون تصريح",
  "Use the hot stick": "استخدام العصا النشطة (أداة العزل)",
  "Used as normal": "يُستخدم بشكل طبيعي",
  "Used for handling chemicals": "يُستخدم للتعامل مع المواد الكيميائية",
  "Using the correct personal lock": "استخدام القفل الشخصي الصحيح",
  "Vehicle color": "لون المركبة",
  "Vehicle maintenance": "صيانة المركبة",
  "Verify that the equipment is de-energized (zero energy)": "التحقق من أن المعدات مفصولة عن الطاقة (انعدام الطاقة)",
  "Verify that the work can be done safely and that hazards are controlled": "التحقق من إمكانية تنفيذ العمل بأمان وسيطرة المخاطر",
  "Verify zero energy": "التحقق من انعدام الطاقة",
  "Very close to the right edge": "قريب جداً من الحافة اليمنى",
  "Visitor Badge": "شارة الزائر",
  "Visitors": "الزوار",
  "Wait and watch": "الانتظار والمراقبة",
  "Wait for it to disappear automatically": "الانتظار حتى تختفي من تلقاء نفسها",
  "Wait for the police": "الانتظار للشرطة",
  "Warn that equipment must not be operated": "التنبيه بأن المعدات لا يجوز تشغيلها",
  "Wash the part with hot water": "غسل الجزء بالماء الساخن",
  "Wash the wound with hot water only": "غسل الجرح بالماء الساخن فقط",
  "Wear PPE": "ارتداء معدات الحماية الشخصية",
  "Wearing safety glasses": "ارتداء نظارات السلامة",
  "Wearing warm clothes in winter": "ارتداء ملابس دافئة في الشتاء",
  "Weather only": "الطقس فقط",
  "Weave between lanes quickly": "التنقل بين المسارات بسرعة",
  "Wet and dry burns": "حروق رطبة وجافة",
  "When a worker owns a padlock": "عندما يمتلك العامل قفلاً شخصياً",
  "Whenever work is done near moving machinery": "كلما تم العمل بالقرب من الآلات المتحركة",
  "White": "أبيض",
  "Wind": "الرياح",
  "Work Permit for office cleaning": "تصريح عمل لتنظيف المكاتب",
  "Work without coordination": "العمل دون تنسيق",
  "Working live": "العمل على المعدات النشطة",
  "Works in the cafeteria": "يعمل في الكافتيريا",
  "Worn only in winter": "يُلبس في الشتاء فقط",
  "Yes, if the supervisor agrees": "نعم، إذا وافق المشرف",
  "Yes, if they are experienced": "نعم، إذا كانوا ذوي خبرة",
};

export function translateOptions(options: string[]): string[] {
  return options.map((o) => AR[o.trim()] ?? o);
}
